# Based on GitHub Actions CMake template
name: PR Checks

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v2
      with:
        path: source

    - name: Create working directory
      run: mkdir -p build

    - name: Configure CMake
      run: cmake -B build -S source -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DPTUNIT=ON

    - name: Build
      run: make -C build -j$(nproc)

    - name: Test
      run: make -C build test
