# Based on GitHub Actions CMake template
name: PR Checks

on: [pull_request]


jobs:
  test:
    runs-on: ${{matrix.runner}}
    strategy:
      matrix:
        build_type: [Release, Debug]
        runner: [ubuntu-latest, windows-latest, macos-latest]

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
      with:
        path: source

    - name: Create working directory
      run: mkdir -p build

    - name: Configure CMake
      run: cmake -B build -S source -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DPTUNIT=ON

    - name: Build
      run: cmake --build build -j

    - name: Test
      run: cd build && ctest
